# Generated by Django 5.1.12 on 2025-09-19 08:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=128)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('initial_referrer', models.TextField(blank=True, default='')),
                ('lang', models.CharField(blank=True, default='', max_length=32)),
                ('tz_offset', models.IntegerField(blank=True, null=True)),
                ('screen_w', models.IntegerField(blank=True, null=True)),
                ('screen_h', models.IntegerField(blank=True, null=True)),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('focus_loss', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('referrer', models.TextField(blank=True, default='')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.visitor')),
            ],
        ),
    ]
