# Generated by Django 5.1.12 on 2025-09-20 19:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('civil', 'Цивільна'), ('criminal', 'Кримінальна')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('descriptive_text', models.TextField(blank=True, default='')),
                ('partial_motivation_text', models.TextField(blank=True, default='')),
                ('facts_text', models.TextField(blank=True, default='')),
                ('model_intro_text', models.TextField(blank=True, default='')),
                ('decisions_json', models.JSONField(blank=True, default=dict)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('spec', models.CharField(choices=[('civil', 'Цивільна'), ('criminal', 'Кримінальна')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(99)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('motivation_text', models.TextField(blank=True, default='')),
                ('resolution_text', models.TextField(blank=True, default='')),
                ('last_autosave_at', models.DateTimeField(blank=True, null=True)),
                ('autosave_version', models.PositiveIntegerField(default=0)),
                ('paste_blocked', models.PositiveIntegerField(default=0)),
                ('keypress_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice.practicaltask')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В черзі'), ('done', 'Готово'), ('failed', 'Помилка')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='practice.practicesession')),
            ],
        ),
    ]
