# Generated by Django 5.1.12 on 2025-09-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltask',
            name='decisions_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='decisions_last_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
