# Generated by Django 5.1.12 on 2025-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicaltask_decisions_cache_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='practicaltask',
            constraint=models.UniqueConstraint(fields=('spec', 'title'), name='uniq_practicaltask_spec_title'),
        ),
    ]
