# Generated by Django 5.1.12 on 2025-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq', '0002_question_tasktype_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='task_type',
            field=models.CharField(choices=[('verbal', 'verbal'), ('logical', 'logical'), ('abstract', 'abstract')], default='verbal', max_length=10),
        ),
    ]
